# Generated by Django 3.0.1 on 2020-01-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
