# Generated by Django 3.0.1 on 2020-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200117_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='nick_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Privado'), (1, 'Publico')], default=0),
        ),
    ]
