# Generated by Django 3.0.1 on 2020-01-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
